// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFGXWvfvOIwYtlmgOqO5W9ZOZXtZut7TQ',
    appId: '1:412054021527:web:3e1d06575f082d3f2e90d2',
    messagingSenderId: '412054021527',
    projectId: 'iot-queue-management',
    authDomain: 'iot-queue-management.firebaseapp.com',
    databaseURL:
        'https://iot-queue-management-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-queue-management.firebasestorage.app',
    measurementId: 'G-J7M4M828ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFGXWvfvOIwYtlmgOqO5W9ZOZXtZut7TQ',
    appId: '1:412054021527:android:ANDROID_APP_ID_HERE',
    messagingSenderId: '412054021527',
    projectId: 'iot-queue-management',
    databaseURL:
        'https://iot-queue-management-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-queue-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFGXWvfvOIwYtlmgOqO5W9ZOZXtZut7TQ',
    appId: '1:412054021527:ios:IOS_APP_ID_HERE',
    messagingSenderId: '412054021527',
    projectId: 'iot-queue-management',
    databaseURL:
        'https://iot-queue-management-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-queue-management.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFGXWvfvOIwYtlmgOqO5W9ZOZXtZut7TQ',
    appId: '1:412054021527:ios:IOS_APP_ID_HERE',
    messagingSenderId: '412054021527',
    projectId: 'iot-queue-management',
    databaseURL:
        'https://iot-queue-management-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-queue-management.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
}
